# Generated by Django 5.2.14 on 2026-07-07 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("hostname", models.CharField(max_length=255)),
                ("ssh_port", models.PositiveSmallIntegerField(default=22)),
                (
                    "log_file_path",
                    models.CharField(
                        help_text="e.g. /var/log/nginx/access.log", max_length=512
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MimirJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Upload"),
                            ("PROCESSING", "Analyzing Log"),
                            ("SUCCESS", "Analysis Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("temp_auth_token", models.CharField(max_length=255, unique=True)),
                (
                    "local_log_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "report_html_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "log_format",
                    models.CharField(
                        choices=[
                            ("COMBINED", "Combined (Nginx/Apache)"),
                            ("COMMON", "Common (Apache)"),
                        ],
                        default="COMBINED",
                        max_length=20,
                    ),
                ),
                ("target_hostname", models.CharField(max_length=255)),
                ("target_port", models.PositiveSmallIntegerField(default=22)),
                ("target_username", models.CharField(max_length=255)),
                ("target_log_path", models.CharField(max_length=512)),
                ("proxy_username", models.CharField(max_length=255)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mimir_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mimir.targetserver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ip", models.GenericIPAddressField()),
                ("scenario", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("detected_at", models.DateTimeField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="mimir.mimirjob",
                    ),
                ),
            ],
        ),
    ]
