# Generated by Django 5.2.14 on 2026-07-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mimir", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityalert",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="securityalert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="LOW",
                max_length=20,
            ),
        ),
    ]
